services:
    cabot.failedlogins.listener:
        class: cabot\failedlogins\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
